name: Build and Test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: mcr.microsoft.com/dotnet/sdk:6.0-alpine

    

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build and Test
      run: |
        cd src
        dotnet build
        dotnet test
