name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.x

    - name: Restore NuGet packages
      run: dotnet restore YourApp.sln

    - name: Build the application
      run: dotnet build YourApp.sln --configuration Release

    - name: Run tests
      run: dotnet test YourApp.sln --configuration Release

    - name: Publish artifacts
      run: dotnet publish YourApp.sln --configuration Release --output ${{ github.workspace }}/publish

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: publish
        path: ${{ github.workspace }}/publish
