name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: mcr.microsoft.com/dotnet/sdk:6.0-alpine

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build
      run: |
        cd src
        dotnet build --configuration Debug
      working-directory: ${{ github.workspace }}

    - name: Copy Artifact
      run: |
        mkdir -p artifacts
        cp src/bin/Debug/net6.0/dotnet-demoapp.dll artifacts/
      working-directory: ${{ github.workspace }}

    - name: Display Artifact
      run: |
        ls artifacts
      working-directory: ${{ github.workspace }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: dotnet-demoapp
        path: artifacts
      if: always()

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Azure CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y azure-cli

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0'

    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: dotnet-demoapp
        path: artifacts

    - name: Log in to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: '<Your-Azure-Web-App-Name>'
        slot-name: 'production'  # Optional: Specify the deployment slot
        package: ./artifacts/dotnet-demoapp.dll
